package myclasses;

import Vmm.DBLoader;
import java.sql.ResultSet;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class AirlineAutoComplete {

    public static void main(String[] args) {
        try {

            String json = " {\n"
                    + " \"airlines\": ["
                    + "  {\n"
                    + "   \"fs\": \"AWK\",\n"
                    + "   \"icao\": \"AWK\",\n"
                    + "   \"name\": \"Airwork (NZ)\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AWN\",\n"
                    + "   \"icao\": \"AWN\",\n"
                    + "   \"name\": \"Air Niamey\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AWS\",\n"
                    + "   \"icao\": \"AWS\",\n"
                    + "   \"name\": \"Arab Wings\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AX\",\n"
                    + "   \"iata\": \"AX\",\n"
                    + "   \"icao\": \"LOF\",\n"
                    + "   \"name\": \"Trans States Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AXY\",\n"
                    + "   \"icao\": \"AXY\",\n"
                    + "   \"name\": \"AIR X Charter\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AY\",\n"
                    + "   \"iata\": \"AY\",\n"
                    + "   \"icao\": \"FIN\",\n"
                    + "   \"name\": \"Finnair\",\n"
                    + "   \"phoneNumber\": \"+ 358 600 140 140\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AYD\",\n"
                    + "   \"iata\": \"Y6\",\n"
                    + "   \"icao\": \"AYD\",\n"
                    + "   \"name\": \"AB Aviation\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AYS\",\n"
                    + "   \"icao\": \"AYS\",\n"
                    + "   \"name\": \"Madagasikara Airways\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AZ\",\n"
                    + "   \"iata\": \"AZ\",\n"
                    + "   \"icao\": \"AZA\",\n"
                    + "   \"name\": \"Alitalia\",\n"
                    + "   \"phoneNumber\": \"1-800-223-5730\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AZI\",\n"
                    + "   \"iata\": \"A2\",\n"
                    + "   \"icao\": \"AZI\",\n"
                    + "   \"name\": \"Astra Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"AZP\",\n"
                    + "   \"iata\": \"ZP\",\n"
                    + "   \"icao\": \"AZP\",\n"
                    + "   \"name\": \"Amaszonas del Paraguay\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B2\",\n"
                    + "   \"iata\": \"B2\",\n"
                    + "   \"icao\": \"BRU\",\n"
                    + "   \"name\": \"Belavia\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B2F\",\n"
                    + "   \"iata\": \"BF\",\n"
                    + "   \"icao\": \"FBU\",\n"
                    + "   \"name\": \"French Bee\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B3*\",\n"
                    + "   \"iata\": \"B3\",\n"
                    + "   \"icao\": \"BTN\",\n"
                    + "   \"name\": \"Bhutan Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B4*\",\n"
                    + "   \"iata\": \"B4\",\n"
                    + "   \"icao\": \"BKA\",\n"
                    + "   \"name\": \"Bankair\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B5\",\n"
                    + "   \"iata\": \"B5\",\n"
                    + "   \"icao\": \"EXZ\",\n"
                    + "   \"name\": \"Fly SAX\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B6\",\n"
                    + "   \"iata\": \"B6\",\n"
                    + "   \"icao\": \"JBU\",\n"
                    + "   \"name\": \"JetBlue Airways\",\n"
                    + "   \"phoneNumber\": \"1-800-538-2583\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B7\",\n"
                    + "   \"iata\": \"B7\",\n"
                    + "   \"icao\": \"UIA\",\n"
                    + "   \"name\": \"UNI Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B8\",\n"
                    + "   \"iata\": \"B8\",\n"
                    + "   \"icao\": \"ERT\",\n"
                    + "   \"name\": \"Eritrean Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B9\",\n"
                    + "   \"iata\": \"B9\",\n"
                    + "   \"icao\": \"IRB\",\n"
                    + "   \"name\": \"Iran Airtour\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"B9*\",\n"
                    + "   \"iata\": \"BD\",\n"
                    + "   \"icao\": \"BYC\",\n"
                    + "   \"name\": \"Cambodia Bayon Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BA\",\n"
                    + "   \"iata\": \"BA\",\n"
                    + "   \"icao\": \"BAW\",\n"
                    + "   \"name\": \"British Airways\",\n"
                    + "   \"phoneNumber\": \"1-800-AIRWAYS\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BAF\",\n"
                    + "   \"icao\": \"BAF\",\n"
                    + "   \"name\": \"Belgian Air Component\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BAI\",\n"
                    + "   \"iata\": \"4B\",\n"
                    + "   \"icao\": \"BTQ\",\n"
                    + "   \"name\": \"Boutique Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BAY\",\n"
                    + "   \"icao\": \"BAY\",\n"
                    + "   \"name\": \"Bravo Airways\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BB\",\n"
                    + "   \"iata\": \"BB\",\n"
                    + "   \"icao\": \"SBS\",\n"
                    + "   \"name\": \"Seaborne Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BBG\",\n"
                    + "   \"iata\": \"BZ\",\n"
                    + "   \"icao\": \"BBG\",\n"
                    + "   \"name\": \"Blue Bird Airways\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BC\",\n"
                    + "   \"iata\": \"BC\",\n"
                    + "   \"icao\": \"SKY\",\n"
                    + "   \"name\": \"Skymark Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BCC\",\n"
                    + "   \"iata\": \"8B\",\n"
                    + "   \"icao\": \"BCC\",\n"
                    + "   \"name\": \"Business Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BDI\",\n"
                    + "   \"icao\": \"BDI\",\n"
                    + "   \"name\": \"BenAir\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BE\",\n"
                    + "   \"iata\": \"BE\",\n"
                    + "   \"icao\": \"BEE\",\n"
                    + "   \"name\": \"Flybe\",\n"
                    + "   \"phoneNumber\": \"00 44 1392 268529\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BEK\",\n"
                    + "   \"iata\": \"Z9\",\n"
                    + "   \"icao\": \"BEK\",\n"
                    + "   \"name\": \"Bek Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BEZ\",\n"
                    + "   \"icao\": \"BEZ\",\n"
                    + "   \"name\": \"Kingfisher Air Service\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BF\",\n"
                    + "   \"iata\": \"BO\",\n"
                    + "   \"icao\": \"BBD\",\n"
                    + "   \"name\": \"Bluebird Nordic\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BF*\",\n"
                    + "   \"icao\": \"RSR\",\n"
                    + "   \"name\": \"Aero-Service\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BG\",\n"
                    + "   \"iata\": \"BG\",\n"
                    + "   \"icao\": \"BBC\",\n"
                    + "   \"name\": \"Biman Bangladesh Airlines\",\n"
                    + "   \"phoneNumber\": \"+880 2911 9995\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BGA\",\n"
                    + "   \"iata\": \"4Y\",\n"
                    + "   \"icao\": \"BGA\",\n"
                    + "   \"name\": \"Airbus Transport International\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BGH\",\n"
                    + "   \"iata\": \"8H\",\n"
                    + "   \"icao\": \"BGH\",\n"
                    + "   \"name\": \"BH Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BGM\",\n"
                    + "   \"iata\": \"2B\",\n"
                    + "   \"icao\": \"BGM\",\n"
                    + "   \"name\": \"Ak Bars Aero\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BGN\",\n"
                    + "   \"iata\": \"BN\",\n"
                    + "   \"icao\": \"BGN\",\n"
                    + "   \"name\": \"Air Inter Transport\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BGT\",\n"
                    + "   \"icao\": \"BGT\",\n"
                    + "   \"name\": \"Bergen Air Transport\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BH\",\n"
                    + "   \"iata\": \"BH\",\n"
                    + "   \"name\": \"Hawkair Aviation\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BHA\",\n"
                    + "   \"iata\": \"U4\",\n"
                    + "   \"icao\": \"BHA\",\n"
                    + "   \"name\": \"Buddha Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BHL\",\n"
                    + "   \"icao\": \"BHL\",\n"
                    + "   \"name\": \"Bristow Helicopters\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BI\",\n"
                    + "   \"iata\": \"BI\",\n"
                    + "   \"icao\": \"RBA\",\n"
                    + "   \"name\": \"Royal Brunei Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BIC\",\n"
                    + "   \"iata\": \"C9\",\n"
                    + "   \"icao\": \"BIC\",\n"
                    + "   \"name\": \"Alphaland Aviation\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BID\",\n"
                    + "   \"icao\": \"BID\",\n"
                    + "   \"name\": \"BinAir\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BIE\",\n"
                    + "   \"iata\": \"ML\",\n"
                    + "   \"icao\": \"BIE\",\n"
                    + "   \"name\": \"Air Mediterranee\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BJ\",\n"
                    + "   \"iata\": \"BJ\",\n"
                    + "   \"icao\": \"LBT\",\n"
                    + "   \"name\": \"Nouvelair Tunisie\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BK\",\n"
                    + "   \"iata\": \"BK\",\n"
                    + "   \"icao\": \"OKA\",\n"
                    + "   \"name\": \"Okay Airways\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BL\",\n"
                    + "   \"iata\": \"BL\",\n"
                    + "   \"icao\": \"PIC\",\n"
                    + "   \"name\": \"Jetstar Pacific\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BM\",\n"
                    + "   \"iata\": \"BM\",\n"
                    + "   \"icao\": \"BMR\",\n"
                    + "   \"name\": \"bmi Regional\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BNC\",\n"
                    + "   \"icao\": \"BNC\",\n"
                    + "   \"name\": \"Sundance Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BOB\",\n"
                    + "   \"icao\": \"BOB\",\n"
                    + "   \"name\": \"powdair\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BOX\",\n"
                    + "   \"iata\": \"3S\",\n"
                    + "   \"icao\": \"BOX\",\n"
                    + "   \"name\": \"AeroLogic\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BP\",\n"
                    + "   \"iata\": \"BP\",\n"
                    + "   \"icao\": \"BOT\",\n"
                    + "   \"name\": \"Air Botswana\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BPS\",\n"
                    + "   \"iata\": \"RP\",\n"
                    + "   \"icao\": \"BPS\",\n"
                    + "   \"name\": \"Base Kft\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BQ*\",\n"
                    + "   \"iata\": \"BQ\",\n"
                    + "   \"icao\": \"BKV\",\n"
                    + "   \"name\": \"Bukovyna Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BQB\",\n"
                    + "   \"icao\": \"BQB\",\n"
                    + "   \"name\": \"Amaszonas del Uruguay\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BR\",\n"
                    + "   \"iata\": \"BR\",\n"
                    + "   \"icao\": \"EVA\",\n"
                    + "   \"name\": \"EVA Air\",\n"
                    + "   \"phoneNumber\": \"+1-800-695-1188\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BRH\",\n"
                    + "   \"icao\": \"BRH\",\n"
                    + "   \"name\": \"Star Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BRL\",\n"
                    + "   \"icao\": \"BRL\",\n"
                    + "   \"name\": \"TopBrass Aviation\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BRP\",\n"
                    + "   \"icao\": \"BRP\",\n"
                    + "   \"name\": \"AeroBratsk\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BS\",\n"
                    + "   \"iata\": \"BS\",\n"
                    + "   \"icao\": \"BIH\",\n"
                    + "   \"name\": \"British International\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BS*\",\n"
                    + "   \"iata\": \"BS\",\n"
                    + "   \"icao\": \"UBG\",\n"
                    + "   \"name\": \"US-Bangla Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BSK\",\n"
                    + "   \"iata\": \"LL\",\n"
                    + "   \"icao\": \"BSK\",\n"
                    + "   \"name\": \"Miami Air International\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BSX\",\n"
                    + "   \"iata\": \"5B\",\n"
                    + "   \"icao\": \"BSX\",\n"
                    + "   \"name\": \"Bassaka Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BT\",\n"
                    + "   \"iata\": \"BT\",\n"
                    + "   \"icao\": \"BTI\",\n"
                    + "   \"name\": \"Air Baltic\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BU*\",\n"
                    + "   \"iata\": \"BU\",\n"
                    + "   \"name\": \"CAA\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BUC\",\n"
                    + "   \"iata\": \"H6\",\n"
                    + "   \"icao\": \"BUC\",\n"
                    + "   \"name\": \"Bulgarian Air Charter\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BV\",\n"
                    + "   \"iata\": \"BV\",\n"
                    + "   \"icao\": \"BPA\",\n"
                    + "   \"name\": \"Blue Panorama Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BVI\",\n"
                    + "   \"iata\": \"4V\",\n"
                    + "   \"icao\": \"BVI\",\n"
                    + "   \"name\": \"BVI Airways\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BVL\",\n"
                    + "   \"iata\": \"LB\",\n"
                    + "   \"icao\": \"BVL\",\n"
                    + "   \"name\": \"Bul Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BVN\",\n"
                    + "   \"icao\": \"BVN\",\n"
                    + "   \"name\": \"Baron Aviation Services\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BW\",\n"
                    + "   \"iata\": \"BW\",\n"
                    + "   \"icao\": \"BWA\",\n"
                    + "   \"name\": \"Caribbean Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BX\",\n"
                    + "   \"iata\": \"BX\",\n"
                    + "   \"icao\": \"ABL\",\n"
                    + "   \"name\": \"Air Busan\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BZ\",\n"
                    + "   \"iata\": \"BZ\",\n"
                    + "   \"icao\": \"KEE\",\n"
                    + "   \"name\": \"Keystone Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"BZ*\",\n"
                    + "   \"iata\": \"BZ\",\n"
                    + "   \"icao\": \"BDA\",\n"
                    + "   \"name\": \"Blue Dart Aviation\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"C2*\",\n"
                    + "   \"iata\": \"C2\",\n"
                    + "   \"icao\": \"CEL\",\n"
                    + "   \"name\": \"CEIBA Intercontinental\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"C2Q\",\n"
                    + "   \"iata\": \"CQ\",\n"
                    + "   \"name\": \"Charterlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"C4*\",\n"
                    + "   \"iata\": \"C4\",\n"
                    + "   \"icao\": \"QAI\",\n"
                    + "   \"name\": \"Conquest Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"C5\",\n"
                    + "   \"iata\": \"C5\",\n"
                    + "   \"icao\": \"UCA\",\n"
                    + "   \"name\": \"CommutAir\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"C6\",\n"
                    + "   \"iata\": \"C6\",\n"
                    + "   \"icao\": \"CJA\",\n"
                    + "   \"name\": \"CanJet Airlines\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"C7*\",\n"
                    + "   \"iata\": \"C7\",\n"
                    + "   \"icao\": \"CIN\",\n"
                    + "   \"name\": \"Cinnamon Air\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"C8\",\n"
                    + "   \"iata\": \"C8\",\n"
                    + "   \"icao\": \"ICV\",\n"
                    + "   \"name\": \"Cargolux Italia\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"CA\",\n"
                    + "   \"iata\": \"CA\",\n"
                    + "   \"icao\": \"CCA\",\n"
                    + "   \"name\": \"Air China\",\n"
                    + "   \"phoneNumber\": \"1-800-986-1985\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"CAC\",\n"
                    + "   \"iata\": \"QC\",\n"
                    + "   \"icao\": \"CRC\",\n"
                    + "   \"name\": \"Camair-Co\",\n"
                    + "   \"active\": true\n"
                    + "  },\n"
                    + "  {\n"
                    + "   \"fs\": \"CAD\",\n"
                    + "   \"iata\": \"8F\",\n"
                    + "   \"icao\": \"CAD\",\n"
                    + "   \"name\": \"Cardig Air\",\n"
                    + "   \"active\": true\n"
                    + "  }"
                    + "]}";
            JSONObject jSONObject = (JSONObject) new JSONParser().parse(json);
            JSONArray array = (JSONArray) jSONObject.get("airlines");
//            System.out.println(array.size());
            for (int i = 0; i < array.size(); i++) {
                JSONObject rowdata = (JSONObject) array.get(i);
                ResultSet rs = DBLoader.executeQuery("select * from airlines where "
                        + "name=\"" + rowdata.get("name") + "\"");
                if (rs.next()) {
                    continue;
                }
                rs.moveToInsertRow();
                rs.updateString("name", rowdata.get("name") + "");
                rs.updateString("icao", rowdata.get("icao") + "");
                rs.updateString("iata", rowdata.get("iata") + "");
                rs.updateString("fs", rowdata.get("fs") + "");
                rs.insertRow();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
